parameters:
  error_level: verbose

  cors.config:
    enabled: true
    allowedHeaders: ['*']
    allowedMethods: ['GET', 'POST', 'OPTIONS', 'PATCH', 'PUT', 'DELETE']
    allowedOrigins: ['https://gadgetgearfrontend.onrender.com']
    exposedHeaders: false
    maxAge: 1000
    supportsCredentials: true